### ISSUE TITLE
PA Showing No Available Recipes

### ISSUE THREAD

**Issue by AhHanie** [FruitsBerriesMelons123/Skyrim-SE-Prosperous-Alchemist#1]
While I was crafting potions, PA suddenly stopped showing optimal recipes. I could fix it by dropping certain ingredients.

Version: Skyrim SE 1.5.97

Screenshot of issue:
https://i.imgur.com/84FgvBj.png

Screenshot of mod list in addition to Skyrim Together:
https://i.imgur.com/aO0s0MI.png

I also have a copy of the save file if needed.

**Comment by FruitsBerriesMelons123** [comment]
Are you using the protected version of PA?

**Comment by FruitsBerriesMelons123** [comment]
Also, do any of the mods you're using modify ingredients?

**Comment by FruitsBerriesMelons123** [comment]
And, yeah if you send me the save file, I'll try to debug it.

**Comment by AhHanie** [comment]
I wasn't using the protected version and there were no mods that modify ingredients.

Save File:
https://drive.google.com/open?id=1cDexRZ6uJElAN-t4VXC_re0Pwrufx4EH

**Comment by AhHanie** [comment]
I also managed to replicate the issue in an environment with only SkyUI and PA with the same type/number of ingredients.

**Comment by FruitsBerriesMelons123** [comment]
Would you mind uploading the more basic save file with just SkyUI and PA too? The other one crashes for me.

**Comment by zwya** [comment]
https://drive.google.com/open?id=1JT5Wtk-qB7MPq-8836iCJ67NKVVGHUrh

**Comment by AhHanie** [comment]
https://drive.google.com/open?id=1xkx9QCSqsaTy3Xtlr5GjRG4f9mkwqVI8

**Comment by FruitsBerriesMelons123** [comment]
[alchemist.zip](https://github.com/FruitsBerriesMelons123/Skyrim-SE-Prosperous-Alchemist/files/4399577/alchemist.zip)
Can you test this one to see if it fixes your problem?

**Comment by FruitsBerriesMelons123** [comment]
[AlchemistFix.zip](https://github.com/FruitsBerriesMelons123/Skyrim-SE-Prosperous-Alchemist/files/4399580/AlchemistFix.zip)
Can you test this one?

**Comment by FruitsBerriesMelons123** [comment]
![image](https://user-images.githubusercontent.com/60863689/77857830-3464cb80-71bd-11ea-972a-fdc0c19e10af.png)

**Comment by AhHanie** [comment]
I have tried the fix and it works. Thank you so much for your time.

**Comment by FruitsBerriesMelons123** [comment]
Oh that was protected version. Here's the standard version:
[AlchemistFixStandard.zip](https://github.com/FruitsBerriesMelons123/Skyrim-SE-Prosperous-Alchemist/files/4399952/AlchemistFixStandard.zip)
